version: "3.9"

services:
  ftb-retro-smp:
    container_name: GTNH-2.2.8
    build: .
    image: gtnh:2.2.8
    volumes:
      - type: bind
        source: /home/hayaka/GTNH-server/Current-World
        target: /data/World
    environment:
      - MYKEY=2G
    ports:
    - "25565:25565"
    restart: on-failure:3
    tty: true
    #net: "host" # maybe use instead of biding ports
    command: >
      bash -c "echo "Gregtech\ New\ Horizons\ 2.2.8!" && 
             java -Xms6G -Xmx6G -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -Dfml.readTimeout=180 -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui
      "
