version: "3.9"

services:
  ftb-retro-smp:
    container_name: FTB-Retro-SMP
    build: .
    volumes:
      - type: bind
        source: /home/hayaka/FTB-Retro/
        target: /data
    environment:
      - MYKEY=2G
    ports:
    - "25565:25565"
    #restart: unless-stopped
    restart: on-failure:3
    tty: true
    #net: "host" # maybe use instead of biding ports
    command: >
      bash -c "echo "Feed\ The\ Beast\ Insanity!"
      && java -Xmx1G -Xms1G -jar craftbukkit.jar
      "
