version: "3.9"

services:
  mc:
    container_name: vanilla-1.20.4
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      ENABLE_ROLLING_LOGS: true
      ENABLE_WHITELIST: true
      DIFFICULTY: "hard"
      MAX_WORLD_SIZE: 25000
      TYPE: "FABRIC"
      VERSION: "1.20.4"
      OVERRIDE_SERVER_PROPERTIES: false
    tty: true
    stdin_open: true
    restart: on-failure:3
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data